services:

  backend:
    image: atulgadakh/scaippss-backend:latest
    container_name: scaips-backend
    ports:
      - "5000:3000"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/scaips_local
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: production

  nginx:
    image: nginx:latest
    container_name: scaips-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: scaips-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: scaips_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: scaips-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
